'use strict';
const assert=require('node:assert/strict'),R=require('./index-revisions.js');
const all={mode:'all'},one={mode:'only',ids:['1']},two={mode:'only',ids:['1','2']};
const source='a'.repeat(64),rev='b'.repeat(32),receipt={kind:'check_revision',phase:'succeeded',source_id:source,levels:all,index_revision:rev};
assert.equal(R.candidate([]),null);
assert.equal(R.candidate([{...receipt,kind:'index_revision'}]),null,'building never proposes an automatic switch');
assert.equal(R.candidate([receipt]),receipt,'read-only reconciliation can restore a checked revision');
assert.equal(R.candidate([receipt,{kind:'check_revision',phase:'failed'}]),null);
assert.equal(R.candidate([{...receipt,index_revision:'../revision'}]),null);
assert.equal(R.matches(receipt,source,all),true);
assert.equal(R.matches(receipt,'c'.repeat(64),all),false);
assert.equal(R.matches(receipt,source,one),false);
assert.equal(R.selection(two),R.selection({mode:'only',ids:['2','1']}));
assert.notEqual(R.selection(all),R.selection(two));
assert.throws(()=>R.selection({mode:'only',ids:[]}));
assert.throws(()=>R.selection({mode:'only',ids:['1','1']}));
const empty=R.useRequest(receipt,source,all,'level',[137,103],null);
assert.equal(empty.approved,true);assert.deepEqual(empty.target,{kind:'empty'});
assert.equal(empty.revision,rev);assert.equal(empty.kind,'use_revision');assert(!empty.options&&!empty.force);
const current={source_id:source,mode:'chip',levels:all,view_id:'d'.repeat(64),state_rev:'27'};
const use=R.useRequest(receipt,source,all,'chip',[137,103],current);
assert.deepEqual(use.target,{kind:'replace',view_id:current.view_id,state_rev:'27'});
assert.throws(()=>R.useRequest(receipt,source,all,'layer',[137,103],current));
assert.throws(()=>R.useRequest(receipt,source,one,'chip',[137,103],current));
console.log('WEB INDEX REVISIONS: ALL OK (explicit build/check/use, exact selection, captured view CAS, no automatic switch)');
