"""Palette definitions: Calibre color table + fill pattern set.

Both tables ship as packaged text files (single sources):
  colornames.def    <name> <rrggbb>, row-major 7x7 palette grid
  fillpatterns.def  <name> <16 four-digit hex words>, row-major
                    5x4 fill grid; MSB = leftmost pixel
Solid/Clear stay fixed in the viewer; every other fill can be
refined in the bitmap editor popup (right-click a slot) - editing
fillpatterns.def re-bases the defaults for everyone.

Preview all patterns:  python -m floe.fillpat
"""

SIZE = 16


def _pkg_path(name):
    import os as _os
    return _os.path.join(
        _os.path.dirname(_os.path.abspath(__file__)), name)


def _load_fill_table():
    """fillpatterns.def: <name> <16 hex words> per line, row-major
    = the 5x4 fill palette grid order (single source, like
    colornames.def)."""
    import sys as _sys
    rows = []
    try:
        with open(_pkg_path("fillpatterns.def")) as f:
            for ln in f:
                ln = ln.strip()
                if not ln or ln.startswith("#"):
                    continue
                parts = ln.split()
                if len(parts) != 1 + SIZE:
                    continue
                try:
                    rows.append((parts[0],
                                 hex_to_rows(" ".join(parts[1:]))))
                except ValueError:
                    continue
    except OSError as e:
        print("floe: fillpatterns.def unreadable (%s) - empty "
              "fill table" % e, file=_sys.stderr)
    return tuple(rows)


FIXED_FILLS = ("solid", "clear")


def default_patterns():
    """Editable copy of the default bitmaps, grid order."""
    return [p for _, p in FILL_PATTERNS]


# the Calibre 7x7 color table: loaded from the packaged
# colornames.def (single source for the palette grid order, the
# layerprops color names and the hex values)
def _load_color_table():
    import os as _os
    import sys as _sys
    path = _os.path.join(_os.path.dirname(_os.path.abspath(
        __file__)), "colornames.def")
    rows = []
    try:
        with open(path) as f:
            for ln in f:
                ln = ln.strip()
                if not ln or ln.startswith("#"):
                    continue
                parts = ln.split()
                if len(parts) < 2:
                    continue
                rows.append((parts[0],
                             "#" + parts[1].lstrip("#").lower()))
    except OSError as e:
        print("floe: colornames.def unreadable (%s) - empty "
              "color table" % e, file=_sys.stderr)
    return tuple(rows)


COLOR_TABLE = _load_color_table()
_COLOR_HEX = {n: h for n, h in COLOR_TABLE}
# first name wins for a shared value (yellow over yellow1 etc.)
_COLOR_NAME = {}
for _n, _h in COLOR_TABLE:
    _COLOR_NAME.setdefault(_h, _n)
_FILL_INDEX = {}


def color_hex(name):
    """layerprops color field -> '#rrggbb' (names from the 7x7
    table, or a literal #hex); None if unknown."""
    if name.startswith("#"):
        return name.lower()
    return _COLOR_HEX.get(name.lower())


def color_name(hexval):
    """'#rrggbb' -> table name, or the #hex itself if unnamed."""
    return _COLOR_NAME.get(hexval.lower(), hexval.lower())


def fill_index(name):
    """fill name (case-insensitive) -> slot index, or None."""
    if not _FILL_INDEX:
        for i, n in enumerate(FILL_NAMES):
            _FILL_INDEX[n.lower()] = i
    return _FILL_INDEX.get(name.lower())


def parse_layerprops(text):
    """Calibre .layerprops lines ->
    [((layer, dt), color, fill, name, f1, f2)]. '2' means 2/0,
    '7.20' means 7/20; comments and malformed lines skipped."""
    rows = []
    for ln in text.splitlines():
        ln = ln.strip()
        if not ln or ln.startswith("#"):
            continue
        parts = ln.split()
        if len(parts) < 3:
            continue
        ld = parts[0].split(".")
        try:
            key = (int(ld[0]),
                   int(ld[1]) if len(ld) > 1 else 0)
        except ValueError:
            continue
        rows.append((key, parts[1], parts[2],
                     parts[3] if len(parts) > 3 else "",
                     parts[4] if len(parts) > 4 else "1",
                     parts[5] if len(parts) > 5 else "1"))
    return rows


def format_layerprops(rows):
    """[( (l, d), color, fill, name, f1, f2 )] -> file text."""
    out = ["# Generated by floe."]
    for (l, d), color, fill, name, f1, f2 in rows:
        ld = "%d" % l if d == 0 else "%d.%d" % (l, d)
        out.append("%s %s %s %s %s %s"
                   % (ld, color, fill,
                      (name or "%d_%d" % (l, d)).replace(" ", "_"),
                      f1, f2))
    return "\n".join(out) + "\n"


def rows_to_hex(rows):
    """'*'/'.' rows -> 16 four-digit hex words ("FFFF 01B4 ..."),
    MSB = leftmost pixel (the on-disk form, user call 2026-08-11)."""
    words = []
    for line in rows.split("\n"):
        v = 0
        for x, c in enumerate(line[:SIZE]):
            if c == "*":
                v |= 1 << (SIZE - 1 - x)
        words.append("%04X" % v)
    return " ".join(words)


def hex_to_rows(hx):
    """16 hex words -> klayout '*'/'.' rows."""
    rows = []
    for w in hx.split():
        v = int(w, 16)
        rows.append("".join(
            "*" if v & (1 << (SIZE - 1 - x)) else "."
            for x in range(SIZE)))
    return "\n".join(rows)


def pattern(name):
    for n, p in FILL_PATTERNS:
        if n == name:
            return p
    raise KeyError(name)


FILL_PATTERNS = _load_fill_table()
FILL_NAMES = tuple(n for n, _ in FILL_PATTERNS)


def _main():
    for name, pat in FILL_PATTERNS:
        print("--", name)
        print(pat)


if __name__ == "__main__":
    _main()
